default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instagram_app_development


test:
  <<: *default
  database: instagram_app_test


production:
  <<: *default
  database: instagram_app_production
  username: instagram_app
  password: <%= ENV['INSTAGRAM_APP_DATABASE_PASSWORD'] %>
